# Generated by Django 4.1.4 on 2023-01-06 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True, verbose_name='Nome')),
            ],
        ),
        migrations.CreateModel(
            name='Subforum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True, verbose_name='Título')),
                ('descriçao', models.TextField(unique=True, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('createdAt', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subforum')),
            ],
        ),
    ]
