# Generated by Django 4.1.4 on 2023-01-05 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120, unique=True, verbose_name='Título')),
                ('texto', models.TextField(verbose_name='Texto')),
                ('subforum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forum.subforum')),
            ],
        ),
    ]
