# Generated by Django 4.1.4 on 2022-12-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='senha',
            field=models.CharField(default=0, max_length=11),
            preserve_default=False,
        ),
    ]
