# Generated by Django 4.1.4 on 2022-12-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_professor_senha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='nomeSocial',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
