# Generated by Django 4.1.4 on 2022-12-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nomeSocial', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=11)),
                ('senha1', models.CharField(max_length=11)),
                ('senha2', models.CharField(max_length=11)),
                ('aniversario', models.DateField(max_length=6)),
            ],
        ),
    ]
