# Generated by Django 4.1.4 on 2023-01-03 21:08

from django.db import migrations
import userprofile.models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', userprofile.models.UserManager()),
            ],
        ),
    ]
